version: "3.0"
services:
  client:
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        STRIPE_PK: ${STRIPE_PK_DEV}

    ports:
      - '3200:3000'
    volumes:
      - './app:/app'

  emulator:
    build:
      context: ./firebase
      dockerfile: ./Dockerfile.firebase
    ports:
      - '4000:4000'
      - '5001:5001'
      - '9099:9099'
      - '8080:8080'
    volumes:
      - './firebase:/firebase'
      - './emulator_data:/firebase/emulator_data'
      
