version: "3.0"
services:
  client:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    environment:
      STRIPE_SK: $STRIPE_SK_DEV
      STRIPE_PK: $STRIPE_PK_DEV
    ports:
      - '3200:3000'
    volumes:
      - './app:/app'

  emulator:
    build:
      context: ./firebase
      dockerfile: ./Dockerfile.firebase
    ports:
      - '4000:4000'
    expose:
      - '9099'
      - '5001'
      - '8080'
    volumes:
      - './firebase:/firebase'
      
