version: "3.0"
services:
  client:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    environment:
      - STRIPE_SK: ${STRIPE_SK_DEV}
      - STRIPE_PK: ${STRIPE_PK_DEV}
    ports:
      - '3200:3000'
    volumes:
      - './app:/app'

      
