FROM node:14
EXPOSE 4000
EXPOSE 9099
EXPOSE 5001
EXPOSE 8080

RUN apt update && apt install default-jdk -y

RUN npm i -g firebase-tools

WORKDIR /firebase
# To replace with STRIPE_SK
# RUN sed -i "s/REPLACE_WITH_STRIPE_SK/$STRIPE_SK/" /firebase/.runtimeconfig.json

# As of now, saving/loading part is not working
ENTRYPOINT firebase emulators:start --import=emulator_data --export-on-exit=emulator_data & cd /firebase/functions && yarn dev
